#!/bin/bash

############################################
#
# This is a for command tutorial
#  Basic syntax
###########################################

for i in {1..10}
do
	echo $i
done

echo "########################################################"
############################################
#
# Syntax with list created by command result
# 
###########################################

for i in `ls`
do
	echo $i
done
