#!/bin/bash

############################################
#
# This Is a while loop command tutorial
#
############################################

## First method
start=1
end=10

while [ $start -lt $end ]
do
	echo "This Is A while Loop --> $start"
	start=$(($start+1))
done

## Second Method With Argumant
echo "======================================================"
start=0
while [ $start -lt $1 ]
do
	echo "This Is A while Loop with Argument --> $start"
	start=$(($start+1))
done

## Third method With User Input
ans="N"

while [ $ans != "Y" -a $ans != "y" ]
do
	echo -n "Do You Want To Exit From Loop (Y/N) --> "
	read ans
	echo "Your Ans Is --> $ans"
done 
